# frozen_string_literal: true

# This code is created and owned by Fairknowe Inc. (FKI) All rights reserved

# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5).to_i + ENV.fetch("GOOD_JOB_MAX_THREADS", 10).to_i %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV.fetch('DEV_DATABASE_URL') %>
  min_messages: warning

test:
  <<: *default
  url: <%= ENV.fetch('TEST_DATABASE_URL') %>

production:
  <<: *default
  url: <%= ENV.fetch('PROD_DATABASE_URL') %>
